language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
# needed for `travis-cargo coveralls --no-sudo`
addons:
  apt:
    sources:
      - sourceline: 'ppa:chris-lea/libsodium'
    packages:
      - libsodium-dev
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev # needed only for `--verify` coveralls flag

os:
  - linux

env:
  - RUST_BACKTRACE=1

branches:
  except:
    - test

notifications:
  irc:
    channels: "chat.freenode.net#zetox"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} || Change view: %{compare_url}"
    on_success: change
    skip_join: true

matrix:
  allow_failures:
  - rust: beta
  - rust: nightly
  - os: osx

sudo: required

before_script:
  - >
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]
    then
        ./scripts/verify-commit-messages.sh "$TRAVIS_COMMIT_RANGE"
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]
    then
        ./scripts/bootstrap-osx.sh
        export PKG_CONFIG_PATH=$HOME/installed_libsodium/lib/pkgconfig:$PKG_CONFIG_PATH
        export LD_LIBRARY_PATH=$HOME/installed_libsodium/lib:$LD_LIBRARY_PATH
    fi

script:
  - travis-cargo clean
  - cargo build --verbose
  - cargo test --verbose
  - |
    if rustc --version | grep -q nightly
    then
        cargo build --features "clippy" \
        && cargo test --features "clippy"
    fi
  - cargo doc

after_success:
  - >
    test $TRAVIS_PULL_REQUEST == "false"
    && (test $TRAVIS_BRANCH == "travis"
    || test $TRAVIS_BRANCH == "master" )
    && bash ./scripts/deploy-gh-pages.sh
  # measure code coverage and upload to coveralls.io (the verify
  # argument mitigates kcov crashes due to malformed debuginfo, at the
  # cost of some speed <https://github.com/huonw/travis-cargo/issues/12>)
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]] \
        && (! rustc --version | grep -q -E 'beta|nightly')
    then
        travis-cargo coveralls --no-sudo --verify # (can) fails
        # NOTE: doc tests aren't included
        KCOV=./kcov/build/src/kcov ./scripts/coverage.sh
    fi
